---
git_user: '{{ lookup("env", "GIT_USERNAME") }}'
git_pass: '{{ lookup("env", "GIT_TOKEN") }}'
controller_user: # saved in tower
controller_password: # saved in tower
controller_base_url: ansauttow.esl.loc
# what is the base EE that is used for building my custom EE
base_ee: registry.redhat.io/ansible-automation-platform-23/ee-supported-rhel8

# what is the name of the new EE being built: Overwrite with requirements FOLDER IN REPO
new_ee: all_ee
# what is the path where the EE build files are stored
path_ee: /root/Ansible_Execution_Environments
# base folder for cloning EE
base_ee_path: /root
# private automation hub host
pah_host: anshubprd01.esl.loc
# ee repo
ee_repo: "https://{{git_user|urlencode()}}:{{git_pass|urlencode()}}@dev.azure.com/ESLFederalCreditUnion/Ansible_Admin/_git/Ansible_Execution_Environment"
# credential name used in AAP
pah_cred: Private_Automation_Hub_Registry
# pah username/pass
pah_user: "{{ gen1_user }}"
pah_pass: "{{ gen1_pword }}"

podman_login1: "podman login --authfile /run/containers/0/auth.json registry.redhat.io"
podman_login2: "podman login --authfile /run/containers/0/auth.json anshubprd01.esl.loc --tls-verify=false"